async function generatePatientSummary(patient) {
  const condition =
    patient.conditions.length > 0
      ? patient.conditions.map(c => c.condition).join(", ")
      : "No known medical condition";

  const medication =
    patient.medications.length > 0
      ? patient.medications.map(m => m.name).join(", ")
      : "No medications";

  const allergy =
    patient.allergies.length > 0
      ? patient.allergies.map(a => a.allergen).join(", ")
      : "No known allergies";

  const observation =
    patient.observations.length > 0
      ? patient.observations.map(o => o.value).join(", ")
      : "No clinical observations";

  return `
PATIENT SUMMARY

Patient Name: ${patient.name}
Age: ${patient.age}
Gender: ${patient.gender}

Medical Conditions:
${condition}

Current Medications:
${medication}

Allergies:
${allergy}

Clinical Observations:
${observation}

Risk Assessment:
The patient requires regular monitoring based on the available clinical information.

Recommendations:
• Continue prescribed medications.
• Schedule regular follow-up appointments.
• Monitor vital signs and symptoms.
• Maintain a healthy lifestyle and follow doctor's advice.

Generated By:
Patient Context AI Agent
Generated On:
${new Date().toLocaleString()}
`;
}

module.exports = generatePatientSummary;